version: '3'

services:
  node:
    image: node:12
    volumes:
      - "./api:/var/www"  
    ports:
      - "4000:4000"
    expose:
      - 4000
    links:
      - mongo
    environment:
      - URL_MONGO=mongodb://Username:password@mongo

  mongo:
    image: mongo:4.0
    volumes:
      - "./mongo/data:/data/db"
    ports: 
      - "27017:27017"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=Username
      - MONGO_INITDB_ROOT_PASSWORD=password